site_name: iDEC 2026 team wiki

theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: blue grey
      accent: cyan

features:
  - navigation.tabs
  - navigation.top
  - navigation.sections
  - content.code.copy
  - search.highlight

markdown_extensions:
  - attr_list
  - md_in_html

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Project: project.md
  - Design: design.md
  - Experiments: experiments.md
  - Results: results.md
  - Human Practices: hp.md
  - Team: team.md

